backend:
  name: git-gateway
  branch: main

media_folder: "slike/uploads"
public_folder: "/slike/uploads"

collections:
  - name: "ttr"
    label: "Tick Tock Rush Blog"
    folder: "content/bimbux/ttr/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
